### ISSUE TITLE
Poor performance/Perma locked thread issue

### ISSUE THREAD

**Issue by ahungry** [fukamachi/clack#93]
To reproduce, run something like siege command like:
```shell
siege -c 150 'http://localhost:5000/example' -t 10S
```
Where the handler for /example is one that is at least 30KB or so of content (in this case, I can reproduce by calling the #'render from cl-emb on file as small as 3KB, but also with a call to cl-who code to produce approximately the same sized file.

After this, the clack server (using hunchentoot) never releases the threads that had hit the thread limit.  Check total threads still locked up with:
```shell
ps huH p $(ps -ef|grep your.app | grep -v grep | awk '{print $2}') | wc -l 
```

To confirm this is a clack issue and not just a hunchentoot failure, I also created a handler that rendered the same HTML from database data (and straight cl-emb files) via the default easy-listener call in hunchentoot and the performance difference between plain hunchentoot and clack is dramatic:
```shell
Pure Hunchentoot without passing through Clack/Caveman2 routes

Lifting the server siege...      done.

Transactions:                    807 hits
Availability:                 100.00 %
Elapsed time:                   9.61 secs
Data transferred:              22.26 MB
Response time:                  1.05 secs
Transaction rate:              83.98 trans/sec
Throughput:                     2.32 MB/sec
Concurrency:                   88.24
Successful transactions:         807
Failed transactions:               0
Longest transaction:            7.88
Shortest transaction:           0.10



Passing through Clack/Caveman2 routes

Lifting the server siege...      done.

Transactions:                    493 hits
Availability:                  84.13 %
Elapsed time:                   9.95 secs
Data transferred:               2.70 MB
Response time:                  1.27 secs
Transaction rate:              49.55 trans/sec
Throughput:                     0.27 MB/sec
Concurrency:                   62.97
Successful transactions:         493
Failed transactions:              93
Longest transaction:            6.71
Shortest transaction:           0.00
```

**Comment by ahungry** [comment]
Results with woo as the server were about 10% better than native hunchentoot and no locked thread issues.

Maybe woo should be the default server?

**Comment by fukamachi** [comment]
Thank you for reporting.

I can reproduce the problem of Hunchentoot worker threads but it will be released in a while.
It would be an issue of Clack.Handler.Hunchentoot related to HTTP/1.1 keep-alive.

And, the lack of performance isn't surprising me since you're using Caveman2 (with some Clack middlewares, probably).
I've noticed Clack middlewares make the web app much slower because they are implemented as CLOS classes and need to dispatch in every run-time.
It might be solved by rewriting them to resolve the `call` method when `build`ing a Clack app, but I never tried it yet.

> Maybe woo should be the default server?

I don't think so. The default server should be portable and easy to setup because it would be run in various developers' environments.
In that sense, Hunchentoot is the best. It doesn't require any foreign C libraries like libev or libuv.

You can change the server to use on production env by specifying `:server` keyword arg to `clackup` (that is why we use Clack :)).
Actually, I don't recommend to use Hunchentoot on production env for several reasons. FastCGI or Woo (it's still &alpha;, though) would be better.

**Comment by ahungry** [comment]
Thanks fukamachi (for this response and all your awesome software) - I suppose you're right about portability being more important (libuv is not very common in repos yet, just had to compile it from source on my production server).

So far so good with woo, if I find anything I'll let you know as the site I have it on does get pretty good traffic.

**Comment by fukamachi** [comment]
The same threads problem can be reproduced even on Hunchentoot with this simple program.

```common-lisp
(ql:quickload :hunchentoot)

(hunchentoot:define-easy-handler (say-hi :uri "/") ()
  (setf (hunchentoot:content-type*) "text/plain")
  "Hi")

(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 4242))
```

It might be an issue of Hunchentoot?

**Comment by ahungry** [comment]
I had a very similar test but could not reproduce under hunchentoot (using straight hunchentoot was actually the first time I avoided the lock thread issue until I swapped for woo).  I am testing on Arch Linux with SBCL.
